### ISSUE TITLE
Multi-inferior support

### ISSUE THREAD

**Issue by simark** [ROCm/ROCgdb#1]
I don't know if multi-inferior support (multiple Linux processes using the GPU)  is on your roadmap, at some point, but as I am reading the code to understand how GDB interacts with the library, I spotted this that would need to be changed:

https://github.com/ROCm-Developer-Tools/ROCgdb/blob/amd-master/gdb/rocm-tdep.c#L615

`get_rocm_inferior_info` gets the info for the current inferior, which may not be the inferior the event is for.  It would be necessary to know to which inferior the event applies, look it up, and possibly pass it down to other functions.

**Comment by jpsamaroo** [comment]
@simark could this potentially be the cause of #5 ?

**Comment by simark** [comment]
I don't think so, you mentioned having multiple threads, not multiple inferiors (processes) under the same gdb.

**Comment by simark** [comment]
Not relevant anymore.  Code has changed a lot since.  Multi-inferior is supported on the devices that allow it.
