### ISSUE TITLE
Asic family name not present in the sysfs

### ISSUE THREAD

**Issue by tekelle** [ROCm/ROCgdb#12]
I am running CentOS 7.9 and ROCm4.3.0.  When I try to run rocgdb I am getting "amd-dbgapi: fatal error: os_agent_id 42028: asic family name not present in the sysfs.
Could not attach process 4832 (rc=-2)

Configuration is:

configure --host=x86_64-pc-linux-gnu --target=x86_64-pc-linux-gnu
                --with-auto-load-dir=$debugdir:$datadir/auto-load
                --with-auto-load-safe-path=$debugdir:$datadir/auto-load
                --with-expat
                --with-gdb-datadir=/opt/rocm-4.3.0/share/rocgdb (relocatable)
                --with-jit-reader-dir=/opt/rocm-4.3.0/lib/gdb (relocatable)
                --without-libunwind-ia64
                --with-lzma
                --with-babeltrace
                --without-intel-pt
                --without-mpfr
                --without-xxhash
                --with-python=/usr
                --with-python-libdir=/usr/lib
                --without-debuginfod
                --without-guile
                --disable-source-highlight
                --with-separate-debug-dir=/opt/rocm-4.3.0/lib/debug (relocatable)

I have:
2 Vega 10 XL/XT [Radeon RX Vega 56/64] (rev c1) and a Vega 10 [Radeon Instinct MI25] (rev 01) cards.

How can this be resolved?  This is a closed system so everything I post will be hand-typed in.

**Comment by ppanchad-amd** [comment]
@tekelle Apologies for the lack of response.  Vega 56/64 and Vega 10 cards are no longer supported in the latest ROCm 6.2. Closing ticket. Thanks!
