### ISSUE TITLE
make failed on CentOS 7.6

### ISSUE THREAD

**Issue by yulingao** [ROCm/ROCgdb#13]
make[2]: Entering directory '/public/home/gh/JJ/ROCgdb-amd-master/sim'
make SIM_PRIMARY_TARGET= all-recursive
make[3]: Entering directory '/public/home/gh/JJ/ROCgdb-amd-master/sim'
  CC       common/common_libcommon_a-portability.o
In file included from common/portability.c:25:0:
common/portability.h:24:5: error: conflicting types for 'getegid'
 int getegid(void);
     ^~~~~~~
In file included from common/portability.c:23:0:
/usr/include/unistd.h:706:16: note: previous declaration of 'getegid' was here
 extern __gid_t getegid (void) __THROW;
                ^~~~~~~
In file included from common/portability.c:25:0:
common/portability.h:28:5: error: conflicting types for 'geteuid'
 int geteuid(void);
     ^~~~~~~
In file included from common/portability.c:23:0:
/usr/include/unistd.h:700:16: note: previous declaration of 'geteuid' was here
 extern __uid_t geteuid (void) __THROW;
                ^~~~~~~
In file included from common/portability.c:25:0:
common/portability.h:40:5: error: conflicting types for 'setgid'
 int setgid(int gid);
     ^~~~~~
In file included from common/portability.c:23:0:
/usr/include/unistd.h:739:12: note: previous declaration of 'setgid' was here
 extern int setgid (__gid_t __gid) __THROW __wur;
            ^~~~~~
In file included from common/portability.c:25:0:
common/portability.h:44:5: error: conflicting types for 'setuid'
 int setuid(int uid);
     ^~~~~~
In file included from common/portability.c:23:0:
/usr/include/unistd.h:722:12: note: previous declaration of 'setuid' was here
 extern int setuid (__uid_t __uid) __THROW __wur;
            ^~~~~~
common/portability.c:28:5: error: conflicting types for 'getegid'
 int getegid(void)
     ^~~~~~~
In file included from common/portability.c:23:0:
/usr/include/unistd.h:706:16: note: previous declaration of 'getegid' was here
 extern __gid_t getegid (void) __THROW;
                ^~~~~~~
common/portability.c:35:5: error: conflicting types for 'geteuid'
 int geteuid(void)
     ^~~~~~~
In file included from common/portability.c:23:0:
/usr/include/unistd.h:700:16: note: previous declaration of 'geteuid' was here
 extern __uid_t geteuid (void) __THROW;
                ^~~~~~~
common/portability.c:56:5: error: conflicting types for 'setgid'
 int setgid(int gid)
     ^~~~~~
In file included from common/portability.c:23:0:
/usr/include/unistd.h:739:12: note: previous declaration of 'setgid' was here
 extern int setgid (__gid_t __gid) __THROW __wur;
            ^~~~~~
common/portability.c:63:5: error: conflicting types for 'setuid'
 int setuid(int uid)
     ^~~~~~
In file included from common/portability.c:23:0:
/usr/include/unistd.h:722:12: note: previous declaration of 'setuid' was here
 extern int setuid (__uid_t __uid) __THROW __wur;
            ^~~~~~
make[3]: *** [Makefile:2017: common/common_libcommon_a-portability.o] Error 1

**Comment by ppanchad-amd** [comment]
@yulingao Apologies for the lack of response. CentOS 7.6 is no longer supported in the latest ROCm 6.2. Closing ticket. Thanks!
