### ISSUE TITLE
Symbol debugging for kernels

### ISSUE THREAD

**Issue by hgtsoi** [ROCm/ROCgdb#14]
Do we have symbol debuging for gpu kernels now? 
I am using ROCgdb shipped with rocm-4.5.2.  When checking local variables or args in rocgdb, it always shows "Optimized".
Wondering it was optimized out indeed or rocgdb does not support symbolic debugging for kernels in rocm-4.5.2?

**Comment by drtpotter** [comment]
The feature doesn't appear to be present in rocm 5.0.2 on the gfx90a architecture either. I've compiled my code using hipcc and all the combinations of "-g" "-ggdb" and even compiler flags like "--offload-arch=gfx90a" but I still can't get local variables to show anything other than <optimized out> after selecting a thread and a lane from within a kernel breakpoint. Is viewing local variables actually supported at the moment?

**Comment by t-tye** [comment]
The current ROCm 5.4 release does support function local variable printing if compiled with -O0 -g. Support for local/shared address space variables should be added in an upcoming release. You do need to have the focus on a specific AMD GPU thread and lane to see the values for that lane.

**Comment by drtpotter** [comment]
Hey folks,

Really looking forward to this feature becoming available! I just tried it with ROCM 5.4.3 on the supported GFX906 architecture and it doesn't look like it's implemented yet.

**Comment by t-tye** [comment]
Printing variables allocated in private memory has been supported for some time now if compiled with -g -O0. If you have a case where it is not it would be good to see a reproduced we can investigate.

**Comment by drtpotter** [comment]
Hi t-tye,

Absolutely, attached is a self contained matrix multiplication code that reproduces the problem. I am using ROCM 5.4.3 on GFX906.

[mat_mult_bugreport.cpp.txt](https://github.com/ROCm-Developer-Tools/ROCgdb/files/11216394/mat_mult_bugreport.cpp.txt)

The goal is to print kernel variables i0 and i1 from within the kernel **mat_mult**, on line 168.

1. Compile the code with the suggested flags

`hipcc -g -O0 mat_mult_bugreport.cpp -o a.out` 

2. Run rocgdb

`rocgdb ./a.out`

3. From within rocgdb set a breakpoint for the kernel

`b mat_mult`

4. If I then execute `run` it skips over the breakpoint for an unknown reason. 

warning: Temporarily disabling breakpoints for unloaded shared library "file:///home/toby/Pelagos/Projects/HIP_Course/old_material/a.out#offset=12288&size=99280"

5. This doesn't work, try recompiling without -O0

`hipcc -g -ggdb mat_mult_bugreport.cpp -o a.out`

6. Run rocgdb again

`rocgdb ./a.out'

7. Within rocgdb set a breakpoint for the kernel

`b mat_mult'

8. Run to the breakpoint

`run`

9. Disable the breakpoint

`disable`

10. Get which thread is running block (0,0,0)

`info threads`

11. Change to the thread that is running block (0,0,0)

`thread 4` (this might be different for you)

12. Switch to lane 0

`lane 0`

13. Walk through a few lines

`n`

14. Try to print variable i0

`print i0`

I get this error

`No symbol "i0" in current context.`

At present there seems to be no way I can get kernel variables to print. Please let me know if this workflow is successful for you. I am giving a [workshop in HIP](https://github.com/pelagos-consulting/HIP_Course.git) soon with a focus on supercomputing. Having this feature work would be so wonderful for my students.

**Comment by ppanchad-amd** [comment]
@hgtsoi Do you still need assistance with this ticket? Thanks

**Comment by taylding-amd** [comment]
Hi @drtpotter, I tried your matrix multiplication code, but I wasn't able to reproduce the bug. I was using ROCm 6.2.2. Would you mind trying again with our latest build?
![image](https://github.com/user-attachments/assets/952c1e63-729c-4f7c-85af-89384eb4105a)
