### ISSUE TITLE
rocgdb not compiling/installing

### ISSUE THREAD

**Issue by tekelle** [ROCm/ROCgdb#15]
I must be missing an option or something.  Downloaded ROCM-5.2.0.  Placed on system and when I go to do the make, I get the following "configure error: amdgcn*-*-* requires rocm-dbgapi to be installed, or use --with-rocm-dbgapi=PATH.

Do I need to do something first before I run the ./configure and make in the base directory?

**Comment by ppanchad-amd** [comment]
@tekelle Apologies for the lack of response.  Can you please check if you still have the issue with the latest ROCm 6.2? If not, please close the ticket. Thanks!

**Comment by darren-amd** [comment]
Hi @tekelle,

I confirmed that this install is working on the latest ROCm version (6.2), and that the AMD Debugger API Library (ROCdbgapi) is included in the ROCm release. Could you please install the latest version of ROCm as well as the dependencies listed here: https://github.com/ROCm/ROCgdb/blob/amd-staging/README-ROCM.md and run it again:
`apt install bison flex gcc make ncurses-dev texinfo g++ zlib1g-dev \
  libexpat-dev python3-dev liblzma-dev libgmp-dev libmpfr-dev`
