### ISSUE TITLE
Is it possible to debug loaded kernels?

### ISSUE THREAD

**Issue by jeageun** [ROCm/ROCgdb#20]
Hi there,

I'm trying to debug the kernel which is loaded using loadCodeObjectFile, but I can't set breakpoint or step into functions.
For the launcher and actual kernel objects are compiled with -g -ggdb -O0 options. However, when I call "hipExtModuleLaunchKernel" which is the function to call actual loaded kernel, it just return to the host, and could not step into the kernel. How could I step into the kernel?

**Comment by ppanchad-amd** [comment]
@jeageun Apologies for the lack of response. Do you still need assistance with this issue? Thanks!
