### ISSUE TITLE
set scheduler-locking on not working in step mode

### ISSUE THREAD

**Issue by hgtsoi** [ROCm/ROCgdb#22]
Envs:
rocgdb, ROCm5.2
Ubuntu 18.04
vega20

When breakpoint hit in one Wave, 

> stepi;

And then, current thread PC step to next asm line, but all other wave threads resumed and run to end.
Is this the expected behavior?

I thought other threads should blocks sinc scheduler-locking was on.

**Comment by ppanchad-amd** [comment]
@hgtsoi Apologies for the lack of response.  Do you still need assistance with this issue.? Thanks!

**Comment by ppanchad-amd** [comment]
Hi @hgtsoi. Closing ticket due to lack of activity. Please feel free to re-open ticket if you still see the issue with the latest ROCm. Thanks!
