### ISSUE TITLE
[Issue]: Missing support for python 3.13 with ROCm 6.2.4

### ISSUE THREAD

**Issue by tpkessler** [ROCm/ROCgdb#31]
### Problem Description

Hi! I'm packaging ROCm for Arch Linux. We're currently preparing the release of Python 3.13. As part of this, I tried to rebuild ROCgdb against the new python, but the build fails,
```
../../gdb/python/py-gdb-readline.c: In function ‘char* gdbpy_readline_wrapper(FILE*, FILE*, const char*)’:
../../gdb/python/py-gdb-readline.c:63:29: error: ‘_PyOS_ReadlineTState’ was not declared in this scope; did you mean ‘PyOS_Readline’?
   63 |       PyEval_RestoreThread (_PyOS_ReadlineTState);
      |                             ^~~~~~~~~~~~~~~~~~~~
      |                             PyOS_Readline
```
There's the commit 8170efad364aa8e062cba3b722b81aca9eda8cf5 that changes the problematic lines. But I'm not sure how to apply it on top of the ROCm 6.2.4 release as the diff between this commit and rocm-6.2.4 is quite large. Could you help me backporting the fixes for Python 3.13 it or point me to a commit on the main brach that I can use to build ROCgdb with Python 3.13?

### Operating System

Arch Linux

### CPU

AMD EPYC 9454P

### GPU

None

### ROCm Version

ROCm 6.2.3

### ROCm Component

ROCgdb

### Additional Information

Configure flags:
```
./configure \
        --prefix=/opt/rocm \
        --program-prefix=roc \
        --disable-binutils \
        --disable-gprofng \
        --disable-gprof \
        --enable-tui \
        --enable-64-bit-bfd \
        --enable-targets="amdgcn-amd-amdhsa" \
        --with-system-readline \
        --with-python=/usr/bin/python \
        --with-expat \
        --with-system-zlib \
        --with-lzma \
        --disable-gdbtk \
        --disable-ld \
        --disable-gas \
        --disable-gdbserver \
        --disable-sim
```

**Comment by lancesix** [comment]
Hi @tpkessler, thanks for the packaging effort!

From what I can see, it seems sufficient to backport the following 2 patches:
- 7ae9ecfd80104a793ed1d836fd4dc0aa1a9c7832
- 8170efad364aa8e062cba3b722b81aca9eda8cf5

With those (which should apply without conflict), I can properly build ROCgdb-6.2 with python3.13 and run the AMDGPU related tests (`make check-gdb TESTS=gdb.rocm/*.exp`).

If you also want to be able to run the python related tests (`make check-gdb TESTS=gdb.python/*.exp`), you will also want to cherry-pick those patches (one has a slight conflict to resolve, I can provide the patch if necessary):
- 60202b0cedbec7bc692e926c9943ab7e7d2504ac
- 1d4ed5907570ef4901f2bbf383e563dc0854bf15

I am no sure we will be able to get those patches in the 6.2 release branch soon.  Are you happy carrying those patches in the packaging until next release?

**Comment by tpkessler** [comment]
Hi @lancesix, thank you very much for your swift reply! With the two patches, ROCgdb builds fine against Python 3.13. Maintaining them for a while is not an issue at all.
